name: AutoPay UI Tests CI

on:
  push:
    branches: [ main ]
    paths:
      - 'autoPay-ui-tests/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'autoPay-ui-tests/**'

jobs:
  autoPay-ui-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: autoPay-ui-tests
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm test