name: AutoPay UI Tests CI

on:
  push:
    branches: [ main ]
    paths:
      - 'autoPay-ui-tests/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'autoPay-ui-tests/**'

jobs:
  autoPay-ui-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: autoPay-ui-tests
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18   # or the version your project requires

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run tests
        run: npm test