name: Merchant Portal UI Tests CI

on:
  push:
    branches: [ main ]
    paths:
      - 'merchant-portal-ui-tests/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'merchant-portal-ui-tests/**'

jobs:
  merchant-portal-ui-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: merchant-portal-ui-tests
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm test