name: Merchant Portal UI Tests CI

on:
  push:
    branches: [ main ]
    paths:
      - 'merchant-portal-ui-tests/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'merchant-portal-ui-tests/**'
  repository_dispatch: 
    types: [run-tests]  # This allows external triggering of this workflow

jobs:
  merchant-portal-ui-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: merchant-portal-ui-tests  # Ensure the tests run in the correct directory
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18  # Or the version your project requires

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run tests
        run: npm test

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: merchant-portal-ui-tests/playwright-report/
      
      - name: Report status back to test-hub-annex
        if: always() && github.event_name == 'repository_dispatch' && github.event.action == 'run-tests'
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.TH_TOKEN }}
          repository: Raymondskkb/test-hub-annex
          event-type: test-results
          client-payload: |
            {
              "project": "merchant-portal-ui-tests",
              "status": "${{ job.status }}",
              "run_url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
              "artifact": "playwright-report"

            }
      
